export const CONSTANTS = {
    ACTION_TYPES: {
        GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
        GET_MESSAGES_ERROR: 'GET_MESSAGES_ERROR',
        ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE'
    }
}